### base config ####
BASE: &BASE
    data_dir: '/scratch/group/p.atm170020.000/2DTurbData/results/Re5000_fkx4fky4_r0.1_b20.0/NoSGS/NX256/dt0.0002_IC1/data/'
    model_save_path: '/scratch/user/u.dp200518/ML_Weights/Base_Emulator/test3.pt'
    params_save_path: '/scratch/user/u.dp200518/ML_Weights/Base_Emulator/test3_parameters.pkl'
    logfile_path: '/scratch/user/u.dp200518/Logfiles/test3.log'

    log_to_screen: !!bool True
    save_model: !!bool True
    save_checkpoint: !!bool True

    train_file_range: [200000, 220000]
    valid_file_range: [310000, 312000]
    batch_size: 4
    target_step: 3
    num_workers: 1
    pin_memory: !!bool True

    gpu: !!bool True
    lr: 1e-5
    scheduler: None #'CosineAnnealingLR'
    weight_decay: 1e-5
    max_epochs: 5
    checkpointing: !!bool False #True

    img_size: 256
    patch_size: 4
    num_frames: 1
    tubelet_size: 1
    in_chans: 2
    encoder_embed_dim: 96 # 192
    encoder_depth: 3 #6
    encoder_num_heads: 3 #6
    decoder_embed_dim: 96 #192
    decoder_depth: 3 #6
    decoder_num_heads: 3 #6
    mlp_ratio: 4.
    num_out_frames: 1
