### base config ####
BASE: &BASE
    data_dir: '/scratch/group/p.atm170020.000/2DTurbData/results/Re5000_fkx4fky4_r0.1_b20.0/NoSGS/NX256/dt0.0002_IC1/'

    exp_dir: '/scratch/user/u.dp200518/SSL-2DTurb/'

    log_to_screen: !!bool True
    log_to_wandb: !!bool False #True
    project: 'SSL-2DTurb'
    group: 'Dhruvit-base-emulator'
    name: '0023'
    diagnostic_logs: !!bool True

    fresh_start: True
    early_stopping: !!bool False

    save_checkpoint: !!bool True

    train_file_range: [200000, 220000]
    valid_file_range: [310000, 312000]
    batch_size: 32 
    target_step: 3
    num_workers: 8
    pin_memory: !!bool True

    gpu: !!bool True
    lr: 5e-4
    scheduler: 'ReduceLROnPlateau'
    warmup: !!bool True
    warmup_startfactor: 0.001 
    warmup_totaliters: 3
    weight_decay: 1e-8
    max_epochs: 500
    checkpointing: !!bool False #True

    train_tendencies: !!bool False #True

    img_size: 256
    patch_size: 4
    num_frames: 2
    tubelet_size: 2
    in_chans: 2
    encoder_embed_dim: 192
    encoder_depth: 4 #6
    encoder_num_heads: 4 #6
    decoder_embed_dim: 96 #192
    decoder_depth: 4 #6
    decoder_num_heads: 4 #6
    mlp_ratio: 4.
    num_out_frames: 1
    patch_recovery: "subpixel_conv"  #["linear", "conv", "subpixel_conv"]

    mae_finetune: False
    mae_finetune_fp: '/scratch/user/u.dp200518/ML_Weights/MAE_Pretrain/TS0_NF1_LRSNone_200epochs_small.pt'
    freeze_layers: ['encoder']



MAE_PRETRAIN: &MAE_PRETRAIN
    <<: *BASE

    target_step: 0

    train_tendencies: !!bool False

    num_frames: 3
    tubelet_size: 3
    num_out_frames: 3  

    mask_ratio: 0.75



MAE_FINETUNE: &MAE_FINETUNE
    <<: *BASE

    project: 'SSL-2DTurb'
    group: 'Dhruvit-MAE-finetune'
    name: '0004'

    train_file_range: [200000, 202000]
    
    batch_size: 32
    max_epochs: 5000

    train_tendencies: !!bool False

    mae_finetune: True
    mae_finetune_fp: '/scratch/user/u.dp200518/SSL-2DTurb/MAE_PRETRAIN/0001/training_checkpoints/best_ckpt.tar'
    freeze_layers: [] # ['encoder']   
